---

- name: Copy etcd systemd unit files
  copy: src="etcd.service" dest="/etc/systemd/system/etcd.service"
  # notify: reload systemd
  when: is_etcd_host == true

- name: reload systemd
  shell: /bin/systemctl daemon-reload
